# Generated by Django 5.0.14 on 2026-04-01 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('deportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRENAMIENTO', 'Entrenamiento'), ('PARTIDO_OFICIAL', 'Partido Oficial'), ('AMISTOSO', 'Partido Amistoso'), ('TERCER_TIEMPO', 'Tercer Tiempo'), ('TORNEO_CLUB', 'Torneo de Club'), ('OTRO', 'Otro Evento')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('rival', models.CharField(blank=True, max_length=150, null=True)),
                ('competencia', models.CharField(blank=True, max_length=150, null=True)),
                ('condicion_partido', models.CharField(blank=True, choices=[('LOCAL', 'En Casa (Local)'), ('VISITANTE', 'Visitante'), ('NEUTRAL', 'Cancha Neutral')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_categoria', to='deportes.categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.club')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='core.socio')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocados', to='eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'jugador')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDE', 'Llegó Tarde'), ('JUSTIFICADO', 'Ausencia Justificada')], max_length=30)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_historial', to='core.socio')),
                ('tomada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_tomadas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'jugador')},
            },
        ),
    ]
