# Generated by Django 5.0.14 on 2026-04-04 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_socio_es_profesor'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePartido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sede_final', models.CharField(blank=True, max_length=200, null=True)),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('estado_planilla', models.CharField(choices=[('PENDIENTE', 'Pendiente de Carga'), ('CARGANDO', 'En Proceso'), ('CERRADA', 'Finalizada y Confirmada')], default='PENDIENTE', max_length=20)),
                ('amarilla_banco', models.BooleanField(default=False)),
                ('suspension_banco', models.BooleanField(default=False, help_text='Sanción de 2 min al oficial de banco')),
                ('roja_banco', models.BooleanField(default=False)),
                ('azul_banco', models.BooleanField(default=False)),
                ('observaciones_arbitro', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoEnPartido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_local', models.BooleanField(default=True)),
                ('nombre_equipo', models.CharField(max_length=150)),
                ('color_camiseta', models.CharField(blank=True, max_length=50, null=True)),
                ('timeouts_usados', models.PositiveSmallIntegerField(default=0)),
                ('detalle_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_stats', to='eventos.detallepartido')),
            ],
            options={
                'verbose_name': 'Equipo en Partido',
                'verbose_name_plural': 'Equipos en Partidos',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dorsal', models.CharField(blank=True, max_length=5, null=True)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('penales_lanzados', models.PositiveIntegerField(default=0)),
                ('penales_convertidos', models.PositiveIntegerField(default=0)),
                ('amarilla', models.BooleanField(default=False)),
                ('suspensiones_2min', models.PositiveSmallIntegerField(default=0, help_text='Máximo 3 suspensiones')),
                ('roja', models.BooleanField(default=False)),
                ('azul', models.BooleanField(default=False)),
                ('detalle_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_stats', to='eventos.detallepartido')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_partidos', to='core.socio')),
            ],
            options={
                'verbose_name': 'Estadística de Jugador',
                'verbose_name_plural': 'Estadísticas de Jugadores',
                'unique_together': {('detalle_partido', 'socio')},
            },
        ),
        migrations.CreateModel(
            name='AccionPartido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minuto', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('GOL', 'Gol de Campo'), ('GOL_7M', 'Gol de 7 metros (Penal)'), ('FALLO_7M', 'Penal Fallado'), ('AMARILLA', 'Tarjeta Amarilla'), ('2MIN', 'Suspensión 2 Minutos'), ('ROJA', 'Tarjeta Roja'), ('AZUL', 'Tarjeta Azul'), ('TIMEOUT', 'Tiempo Muerto'), ('OTRO', 'Otro Evento')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='eventos.detallepartido')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_equipo', to='eventos.equipoenpartido')),
                ('jugador_stats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.estadisticajugador')),
            ],
            options={
                'verbose_name': 'Acción de Partido',
                'verbose_name_plural': 'Acciones de Partidos',
                'ordering': ['minuto', 'id'],
            },
        ),
    ]
