# Generated by Django 5.0.14 on 2026-04-01 13:08

import admin_club.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=admin_club.models.logo_path)),
                ('color_primario', models.CharField(default='#2563eb', help_text='Formato Hex (#FFFFFF)', max_length=7)),
                ('color_secundario', models.CharField(default='#1e40af', help_text='Formato Hex (#FFFFFF)', max_length=7)),
                ('dia_vencimiento_cuota', models.IntegerField(default=10, help_text='Día del mes en que vence la cuota.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('dias_gracia', models.IntegerField(default=5)),
                ('porcentaje_mora', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCobrable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CUOTA', 'Cuota Social'), ('SEGURO', 'Seguro Deportivo'), ('FEDERACION', 'Ficha Federativa'), ('ARBITRAJE', 'Arancel Arbitral'), ('OTRO', 'Otro Concepto')], max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='admin_club.temporada')),
            ],
            options={
                'unique_together': {('temporada', 'tipo', 'descripcion')},
            },
        ),
    ]
