# Generated by Django 5.0.14 on 2026-04-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='nombre_institucional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
