# Generated by Django 5.0.14 on 2026-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_club', '0002_clubconfig_direccion_clubconfig_email_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='inicio_ciclo_contable',
            field=models.DateField(blank=True, help_text='Fecha desde la cual se empieza a contar la deuda para elegibilidad deportiva.', null=True),
        ),
    ]
