# Generated by Django 5.0.14 on 2026-04-03 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_club', '0003_clubconfig_inicio_ciclo_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='descuento_2_hermanos',
            field=models.IntegerField(default=15, help_text='% de descuento con 2 miembros activos del mismo grupo familiar.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='descuento_3_hermanos',
            field=models.IntegerField(default=25, help_text='% de descuento con 3 miembros activos del mismo grupo familiar.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='descuento_4_mas_hermanos',
            field=models.IntegerField(default=30, help_text='% de descuento con 4 o más miembros activos del mismo grupo familiar.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
