# Generated by Django 5.0.14 on 2026-04-01 14:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ej: Fecha 3 vs Club Mitre', max_length=200)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PLANEADA', 'Planeada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PLANEADA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_locales', to='core.club')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CajaJornada',
            fields=[
                ('jornada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance_caja', serialize=False, to='jornada_local.jornada')),
                ('egreso_arbitros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('egreso_viaticos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('otros_egresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('efectivo_sobrante_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lo que el club se queda en mano', max_digits=12)),
                ('rendida_a_tesoreria', models.BooleanField(default=False)),
                ('fecha_rendicion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonacionCantina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('producto', models.CharField(help_text='Ej: Bizcochuelo, 10 empanadas, pack gaseosas', max_length=150)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('valorizado_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Para medir el aporte monetario de la donación', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_cantina', to='core.socio')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='jornada_local.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='VentaJornada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Venta de Entrada'), ('BUFFET', 'Venta Cantina / Buffet'), ('SORTEO', 'Rifa / Sorteo')], max_length=30)),
                ('metodo_pago', models.CharField(default='EFECTIVO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='jornada_local.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tarea', models.CharField(choices=[('ENTRADAS', 'Cobro de Entradas'), ('CANTINA', 'Atención de Cantina'), ('MESA', 'Mesa de Control / Planilla'), ('LIMPIEZA', 'Limpieza y Orden'), ('PLANILLERO', 'Planillero / Veedor'), ('OTRO', 'Otros')], max_length=50)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('cumplido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='jornada_local.jornada')),
                ('persona', models.ForeignKey(help_text='Tanto el socio como sus tutores pueden ser voluntarios.', on_delete=django.db.models.deletion.CASCADE, related_name='voluntariados', to='core.socio')),
            ],
        ),
    ]
