# Generated by Django 5.0.14 on 2026-04-01 14:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('jornada_local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajajornada',
            name='efectivo_declarado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto entregado físicamente por el voluntario', max_digits=12),
        ),
        migrations.AddField(
            model_name='cajajornada',
            name='observaciones_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='access_pin',
            field=models.CharField(blank=True, help_text='PIN temporal para que voluntarios operen sin login.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ventajornada',
            name='socio_comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.socio'),
        ),
        migrations.AlterField(
            model_name='ventajornada',
            name='metodo_pago',
            field=models.CharField(default='EFECTIVO', help_text='EFECTIVO, TRANSFERENCIA, QR', max_length=50),
        ),
    ]
