# Generated by Django 5.2.8 on 2026-04-04 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_socio_es_profesor'),
        ('jornada_local', '0002_cajajornada_efectivo_declarado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaVoluntario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_declarado', models.CharField(max_length=150)),
                ('dni_declarado', models.CharField(max_length=20)),
                ('tarea', models.CharField(choices=[('ENTRADAS', 'Cobro de Entradas'), ('CANTINA', 'Atención de Cantina'), ('MESA', 'Mesa de Control / Planilla'), ('LIMPIEZA', 'Limpieza y Orden'), ('PLANILLERO', 'Planillero / Veedor'), ('OTRO', 'Otros')], max_length=50)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('puntos_asignados', models.PositiveIntegerField(default=10, help_text='Puntos base por turno cumplido.')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='jornada_local.jornada')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_eventos', to='core.socio')),
            ],
        ),
        migrations.CreateModel(
            name='EgresoJornada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('SUMINISTROS', 'Suministros / Buffet'), ('VIATICOS', 'Viáticos'), ('LIMPIEZA', 'Limpieza'), ('OTRO', 'Otros')], default='OTRO', max_length=30)),
                ('descripcion', models.CharField(help_text='Ej: Compra de 2 bolsas de hielo', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='jornada_local.jornada')),
            ],
        ),
    ]
