# Generated by Django 5.0.14 on 2026-04-01 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_corriente', to='core.socio')),
            ],
            options={
                'verbose_name': 'Cuenta Corriente',
                'verbose_name_plural': 'Cuentas Corrientes',
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CUOTA', 'Cuota Mensual'), ('PAGO', 'Pago de Socio'), ('MORA', 'Recargo por Mora'), ('ARBITRAJE', 'Arancel Arbitral'), ('TERCER_TIEMPO', 'Tercer Tiempo'), ('SEGURO', 'Seguro Federativo'), ('AJUSTE', 'Ajuste / Corrección'), ('SALDO_INICIAL', 'Saldo Inicial / Deuda Histórica')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_generados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cuentacorriente')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
