# Generated by Django 5.0.14 on 2026-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia / Banco'), ('MERCADOPAGO', 'Mercado Pago'), ('OTRO', 'Otro / Ajuste')], default='EFECTIVO', max_length=50, null=True),
        ),
    ]
