# Generated by Django 5.0.14 on 2026-04-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_movimientofinanciero_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo',
            field=models.CharField(choices=[('CUOTA', 'Cuota Mensual'), ('PAGO', 'Pago de Socio'), ('MORA', 'Recargo por Mora'), ('ARBITRAJE', 'Arancel Arbitral'), ('TERCER_TIEMPO', 'Tercer Tiempo'), ('SEGURO', 'Seguro Federativo'), ('AJUSTE', 'Ajuste / Corrección'), ('BECA', 'Bonificación por Beca'), ('SALDO_INICIAL', 'Saldo Inicial / Deuda Histórica')], max_length=30),
        ),
    ]
