# Generated by Django 5.0.14 on 2026-04-03 18:55

import django.db.models.deletion
import finanzas.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_primer_ingreso_and_socio_role'),
        ('finanzas', '0003_alter_movimientofinanciero_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_declarado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_declarada', models.DateField()),
                ('descripcion', models.CharField(help_text='Ej: Cuota Abril 2026', max_length=255)),
                ('comprobante', models.ImageField(blank=True, help_text='Foto o captura del comprobante de transferencia (opcional)', null=True, upload_to=finanzas.models.comprobante_path)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('VALIDADO', 'Validado — Recibo Generado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('observacion_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo para mostrarle al socio.', null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movimiento_generado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aviso_origen', to='finanzas.movimientofinanciero')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_pago', to='core.socio')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso de Pago',
                'verbose_name_plural': 'Avisos de Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
