# Generated by Django 5.0.14 on 2026-04-03 20:26

import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_add_aviso_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisopago',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='Foto o captura del comprobante de transferencia (opcional)', max_length=500, null=True, upload_to=finanzas.models.comprobante_path),
        ),
    ]
