# Generated by Django 5.0.14 on 2026-04-01 13:00

import deportes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('MIXTO', 'Mixto')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DNI', 'DNI (Frente y Dorso)'), ('AUTORIZACION_TUTOR', 'Autorización Tutor (Menores)'), ('CONSENTIMIENTO_IMAGEN', 'Consentimiento de Imagen'), ('APTO_FISICO', 'Certificado de Apto Físico'), ('FICHA_FEDERATIVA', 'Ficha de Federación'), ('OTRO', 'Otro Documento')], max_length=50)),
                ('archivo', models.FileField(upload_to=deportes.models.documento_path)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.socio')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_subidos', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_validados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDeportivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posicion_principal', models.CharField(blank=True, choices=[('ARQUERO', 'Arquero'), ('EXTREMO_IZQ', 'Extremo Izquierdo'), ('EXTREMO_DER', 'Extremo Derecho'), ('LATERAL_IZQ', 'Lateral Izquierdo'), ('LATERAL_DER', 'Lateral Derecho'), ('CENTRAL', 'Central'), ('PIVOT', 'Pivot'), ('ENTRENADOR', 'Entrenador'), ('AYUDANTE', 'Ayudante Técnico'), ('DELEGADO', 'Delegado')], max_length=30, null=True)),
                ('posicion_secundaria', models.CharField(blank=True, choices=[('ARQUERO', 'Arquero'), ('EXTREMO_IZQ', 'Extremo Izquierdo'), ('EXTREMO_DER', 'Extremo Derecho'), ('LATERAL_IZQ', 'Lateral Izquierdo'), ('LATERAL_DER', 'Lateral Derecho'), ('CENTRAL', 'Central'), ('PIVOT', 'Pivot'), ('ENTRENADOR', 'Entrenador'), ('AYUDANTE', 'Ayudante Técnico'), ('DELEGADO', 'Delegado')], max_length=30, null=True)),
                ('mano_habil', models.CharField(blank=True, choices=[('DERECHA', 'Derecha'), ('IZQUIERDA', 'Izquierda'), ('AMBIDIESTRO', 'Ambidiestro')], max_length=20, null=True)),
                ('altura_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('nro_camiseta', models.PositiveIntegerField(blank=True, null=True)),
                ('nro_federacion', models.CharField(blank=True, max_length=50, null=True)),
                ('habilitado_federacion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='deportes.categoria')),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_deportivo', to='core.socio')),
            ],
        ),
    ]
