# Generated by Django 5.0.14 on 2026-04-01 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionProfe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_especifico', models.CharField(blank=True, help_text='Ej: Preparador Físico, Ayudante, Profe Principal', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores_asignados', to='deportes.categoria')),
                ('usuario_profe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Profesor',
                'verbose_name_plural': 'Asignaciones de Profesores',
                'unique_together': {('usuario_profe', 'categoria')},
            },
        ),
    ]
