# Generated by Django 5.0.14 on 2026-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0002_asignacionprofe'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de edad (0=Mayores, 1=Juniors, 2=Juveniles, etc. o viceversa)'),
        ),
    ]
