# Generated by Django 5.0.14 on 2026-04-02 14:38

import deportes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0003_categoria_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodigital',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=deportes.models.documento_path),
        ),
    ]
