# Generated by Django 5.0.14 on 2026-04-03 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grupo_familiar_y_descuentos_club'),
        ('deportes', '0004_alter_documentodigital_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_lesion', models.DateField()),
                ('fecha_probable_alta', models.DateField(blank=True, null=True)),
                ('fecha_alta_real', models.DateField(blank=True, null=True)),
                ('contexto', models.CharField(choices=[('PARTIDO_OFICIAL', 'Partido Oficial'), ('PARTIDO_AMISTOSO', 'Partido Amistoso'), ('ENTRENAMIENTO', 'Entrenamiento'), ('PARTICULAR', 'Particular / Fuera del club')], max_length=50)),
                ('diagnostico', models.TextField()),
                ('uso_seguro', models.BooleanField(default=False)),
                ('observaciones_seguro', models.TextField(blank=True, help_text='Datos de la póliza, nro siniestro, etc.', null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RECUPERADA', 'Recuperada')], default='ACTIVA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesiones', to='core.socio')),
            ],
            options={
                'verbose_name': 'Lesión',
                'verbose_name_plural': 'Lesiones',
                'ordering': ['-fecha_lesion'],
            },
        ),
    ]
