# Generated by Django 5.0.14 on 2026-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0005_lesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, help_text='Permite desactivar categorías que el club no utiliza (ej. Senior)'),
        ),
    ]
