# Generated by Django 5.0.14 on 2026-04-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='subdominio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
