# Generated by Django 5.0.14 on 2026-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_club_subdominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='dni_tutor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='mano_habil',
            field=models.CharField(choices=[('DER', 'Diestro'), ('IZQ', 'Zurdo')], default='DER', max_length=10),
        ),
        migrations.AddField(
            model_name='socio',
            name='nombre_tutor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='parentesco_tutor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='posicion_habitual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='tel_tutor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
