# Generated by Django 5.0.14 on 2026-04-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_socio_altura_socio_dni_tutor_socio_mano_habil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro / No especifica')], default='MASCULINO', max_length=20),
        ),
    ]
