# Generated by Django 5.0.14 on 2026-04-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_socio_grupo_sanguineo_socio_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro / No especifica')], max_length=20, null=True),
        ),
    ]
