# Generated by Django 5.0.14 on 2026-04-02 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_socio_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='socios/fotos/'),
        ),
        migrations.AddField(
            model_name='socio',
            name='porcentaje_beca',
            field=models.IntegerField(default=0, help_text='Porcentaje de bonificación sobre la cuota mensual', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
