# Generated by Django 5.0.14 on 2026-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_socio_foto_socio_porcentaje_beca'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
