# Generated by Django 5.0.14 on 2026-04-03 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_socio_domicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Familia García', max_length=200)),
                ('apellido_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_familiares', to='core.club')),
            ],
            options={
                'verbose_name': 'Grupo Familiar',
                'verbose_name_plural': 'Grupos Familiares',
                'unique_together': {('club', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='socio',
            name='grupo_familiar',
            field=models.ForeignKey(blank=True, help_text='Grupo familiar al que pertenece. Permite calcular descuentos por hermanos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socios', to='core.grupofamiliar'),
        ),
    ]
