# Generated by Django 5.0.14 on 2026-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grupo_familiar_y_descuentos_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
