# Generated by Django 5.0.14 on 2026-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_socio_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='posicion_habitual',
            field=models.CharField(blank=True, choices=[('ARQUERO', 'Arquero'), ('EXTREMO_IZQ', 'Extremo Izquierdo'), ('EXTREMO_DER', 'Extremo Derecho'), ('LATERAL_IZQ', 'Lateral Izquierdo'), ('LATERAL_DER', 'Lateral Derecho'), ('CENTRAL', 'Central'), ('PIVOT', 'Pivot')], max_length=100, null=True),
        ),
    ]
