# Generated by Django 5.0.14 on 2026-04-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_socio_observaciones_alter_socio_posicion_habitual'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primer_ingreso',
            field=models.BooleanField(default=False, help_text='Si True, el socio debe cambiar su contraseña al primer login.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / Administrativo'), ('PROFESOR', 'Profesor'), ('SOCIO', 'Socio (Portal Autogestión)'), ('SOCIO_TUTOR', 'Socio / Tutor'), ('DIRIGENTE', 'Dirigente / Comisión')], default='SOCIO_TUTOR', max_length=50),
        ),
    ]
