# Generated by Django 5.0.14 on 2026-04-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_primer_ingreso_and_socio_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='es_profesor',
            field=models.BooleanField(default=False, help_text='Marcar para crear usuario Profesor y asignar como Cuerpo Técnico'),
        ),
    ]
