# Generated by Django 5.0.14 on 2026-04-01 13:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_esperado_sistema', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='core.club')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_gestionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoRecibido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_pesos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto real ingresado (Ej: si se paga con descuento)', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('MP_QR', 'Mercado Pago (QR)'), ('MP_LINK', 'Mercado Pago (Link)'), ('DEBITO_AUTOMATICO', 'Débito Automático'), ('OTROS', 'Otros')], default='EFECTIVO', max_length=30)),
                ('referencia_operacion', models.CharField(blank=True, max_length=150, null=True)),
                ('comprobante_img', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='tesoreria.cajadiaria')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='core.socio')),
                ('usuario_cobrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cobrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMerchandising',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('categoria', models.CharField(choices=[('INDUMENTARIA', 'Indumentaria Club'), ('ELEMENTO', 'Elementos Deportivos'), ('BEBIDA', 'Bebidas/Cantina'), ('MERCH', 'Merchandising')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.club')),
            ],
        ),
    ]
